// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RevitToIfcScheduler.Context;

#nullable disable

namespace RevitToIfcScheduler.Migrations.PostgreSQL
{
    [DbContext(typeof(PostgreSQLRevitIfcContext))]
    partial class PostgreSQLRevitIfcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RevitToIfcScheduler.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("RevitToIfcScheduler.Models.ConversionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DerivativeUrn")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileUrn")
                        .HasColumnType("text");

                    b.Property<string>("FolderId")
                        .HasColumnType("text");

                    b.Property<string>("FolderUrl")
                        .HasColumnType("text");

                    b.Property<string>("HubId")
                        .HasColumnType("text");

                    b.Property<string>("IfcSettingsSetName")
                        .HasColumnType("text");

                    b.Property<string>("InputStorageLocation")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompositeDesign")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<DateTime>("JobCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JobFinished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OutputStorageLocation")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobScheduleId");

                    b.ToTable("ConversionJobs");
                });

            modelBuilder.Entity("RevitToIfcScheduler.Models.IfcSettingsSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IfcSettingsSets");
                });

            modelBuilder.Entity("RevitToIfcScheduler.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Cron")
                        .HasColumnType("text");

                    b.Property<string>("EditedBy")
                        .HasColumnType("text");

                    b.Property<string>("HubId")
                        .HasColumnType("text");

                    b.Property<string>("IfcSettingsName")
                        .HasColumnType("text");

                    b.Property<int?>("LastFileCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SerializedFileUrns")
                        .HasColumnType("text");

                    b.Property<string>("SerializedFolderUrns")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("RevitToIfcScheduler.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutodeskId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefresh")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedToken")
                        .HasColumnType("text");

                    b.Property<string>("HashedSessionKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("SerializedPermissions")
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RevitToIfcScheduler.Models.ConversionJob", b =>
                {
                    b.HasOne("RevitToIfcScheduler.Models.Schedule", "JobSchedule")
                        .WithMany()
                        .HasForeignKey("JobScheduleId");

                    b.Navigation("JobSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
